/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz.nuestrosFormularios;

import interfaz.raven.scrollbar.ScrollBarCustom;

/**
 *
 * @author matias
 */
public class FormularioAltaProductoConScroll extends javax.swing.JPanel {

    /**
     * Creates new form FormularioAltaProductoConScroll
     */
    public FormularioAltaProductoConScroll() {
        initComponents();
        sp.getViewport().setOpaque(false);
        sp.setVerticalScrollBar(new ScrollBarCustom());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sp = new javax.swing.JScrollPane();
        formularioAltaProducto11 = new interfaz.nuestrosFormularios.FormularioAltaProducto();

        sp.setBorder(null);
        sp.setOpaque(false);
        sp.setViewportView(formularioAltaProducto11);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private interfaz.nuestrosFormularios.FormularioAltaProducto formularioAltaProducto11;
    private javax.swing.JScrollPane sp;
    // End of variables declaration//GEN-END:variables
}
